### ISSUE TITLE
[9 beta] [10 beta][Ubuntu16.04] Flag de idioma no detectado correctamente

### ISSUE THREAD

**Issue by cibersheep** [Utodev/ngPAWS#12]
Parece que no puedo hacer que el flag 12 tenga el valor correcto.
En `/PRO 1` me he asegurado que haya  `BSET 12 5` peor al compilar y escribir ayuda (con el archivo base sin modificar) sale en inglés. Al parecer, el flat 12 vale 9 (001001) por el sistema lo toma como inglés. He mirado en Mcarras Quest y vale 41 (101001).

No he encontrado forma de modificarlo (quitando el flag o dándole valor 0 no tiene ningún efecto). ¿Es un bug?

**Comment by cibersheep** [comment]
Parece tener relación con #11

**Comment by Utodev** [comment]
Da la impresión de que no se está ejecutando bien el proceso 1, aunque como dices es más cosa de la issue #11. Al no ejecutarse el proceso no se ejecuta el BSET. Cierro y a ver si podemos reproducir el #11 de alguna manera.
