### ISSUE TITLE
[10beta][CLi Compiler] Images must be in root folder

### ISSUE THREAD

**Issue by cibersheep** [Utodev/ngPAWS#16]
When compile an adventure, using command line compiler or IDE have different behaviour:
Having an structure like:
```
/dat/loc01.png
/code.txp
/loc01.png
```
Meanwhile IDE (graphical tool) looks for images in /dat folder, command line compiler looks for images in / (at the same level of code.txp). So, two copies of the same image (loc01.png) must be provided.

**Comment by Utodev** [comment]
El IDE organiza las aventuras de una manera concreta que él conoce, y trabaja con ello. Una de las cosas que hace es mantener las imágenes en una carpeta. Si tienes que trabajar con y sin IDE a la vez al usar txtpaws tendrás que pasarle el path (opción -i sino recuerdo mal, pero ejecútalo sin parámetros )

**Comment by cibersheep** [comment]
Oooooook.
No sabía esto yo ^__.^

Bien, entonces, se puede conseguir:
`./txtpaws -I./dat/ code.txp`

Excelente. Gracias
