### ISSUE TITLE
[webite] Typo

### ISSUE THREAD

**Issue by cibersheep** [Utodev/ngPAWS#22]
There's a little typo at http://www.ngpaws.com/es.html#Plugins
"pueden ayudaros a hacer mejores juegos:/p> " should say "pueden ayudaros a hacer mejores juegos: "

;)
![imatge](https://cloud.githubusercontent.com/assets/6640041/25463563/7f609c64-2af7-11e7-8fd5-fddf913c76e1.png)

**Comment by Crispinophur** [comment]
There's a minor typo at
https://github.com/Utodev/ngPAWS/wiki/Backwards-compatibility#condacts-compatibiliy
at [PAUSE]:
![screenshot at 2017-09-24 09 23 04](https://user-images.githubusercontent.com/32235716/30780454-5eed7a9e-a10b-11e7-8228-b7d59a5bff79.png)
 "but holds he game completely" should be "but holds the game completely"

**Comment by Utodev** [comment]
I've fixed both typos, thanks!
