### ISSUE TITLE
Bug fixes and minor improvements in the wiki

### ISSUE THREAD

**Issue by 8bat** [Utodev/ngPAWS#25]
I've created [an ngPAWS-based game](https://8bat.github.io/vbca/play/) as part of a wider project to adapt old 8-bit adventures.

While reading the admirably thorough documentation, I came across several issues - some typos, some formatting problems.  GitHub doesn't let you create wiki pull requests, so this is an informal PR for the fixes.

I used [this process for forking a wiki](https://gist.github.com/larrybotha/10650410) to [create a copy with a bunch of fixes](https://github.com/8bat/ngPAWS/wiki).  Here's a link to [review the changes](https://github.com/8bat/ngPAWS/wiki/_compare/c4865aeddecd8f45d5056521cf44918dda2a4804...de8006eeaea8584ae85ee4a21b4f5a0ffa4725e5).  According to the page I followed, the only way for you to merge the changes is to clone `Utodev/ngPAWS.wiki.git` on the command-line, pull changes from `8bat/ngPAWS.wiki.git`, and push them back to your repo.

**Comment by Utodev** [comment]
First of all, thank you for using ngPAWS and many thanks for taking the time to fix all those typos and format issues. I belive the links started to fail after a Github update, but I haven't realized it was cause empty space between the brackets and square brackets parts of the link.

I have pulled your changes and I belive it's all fixed now. I'll take some time now manually fix other user corrections that are pending for some time.

Great job, thanks!

**Comment by Utodev** [comment]
I've merged your pull request too after checking it, thanks!
