### ISSUE TITLE
[aesthetics] «X» y «EX» 

### ISSUE THREAD

**Issue by cibersheep** [Utodev/ngPAWS#36]
Una cosa curiosa:
 -Si se escribe:«X» muestra las salidas (y eso está bien)
 -Si se escribe «X antorcha», examina la antorcha (lo que mola) pero debería ser «EX antorcha» :D

**Comment by Utodev** [comment]
It's a feature!

Originally spanish adventures used X as a per "eXits", but later adventures created with Inform used X as per eXamine. To be able to make both solutions work, ngPAWS (and as far as I know at least infSP and AGE spanish engines) does what you just discovered:  X + Name =  EXAMINE Name, just "X" = EXITS

**Comment by cibersheep** [comment]
Then I can say: It is rrrrrrreally cool feature. Luv'd it
