### ISSUE TITLE
Falta libreria "database.start.spanish"

### ISSUE THREAD

**Issue by netskaven** [Utodev/ngPAWS#4]
En el paquete ES de Linux falta añadir la libreria "database.start.spanish" y la "database.start" esta en ingles.

**Comment by Utodev** [comment]
Ok, lo corregiré. Por ahora bajatela de aquí:

https://raw.githubusercontent.com/Utodev/ngPAWS/master/installation_aux_files/database.start.spanish

**Comment by netskaven** [comment]
La tenia localizada, el reporte es para que quede el paquete fino  ;)

**Comment by Utodev** [comment]
Perfecto, luego lo arreglo, gracias por el aviso :)

**Comment by Utodev** [comment]
Fixed!
