### ISSUE TITLE
ngPAWS Licensing Ambiguity

### ISSUE THREAD

**Issue by scott-martinez** [Utodev/ngPAWS#5]
From reviewing the the README, I understand that ngPAWS is released under "the GPL license." I find a copy of GPL version 2 in the git repo but there is an ambiguity: Is ngPAWS GPL-version-2-only or GPL-version-2-or-any-later-version? My hope is that the "any later version" wording applies. Can you please clarify this by updating the README?

There is some boilerplate that can be used to be clear, from http://www.gnu.org/licenses/gpl-howto.html that can be inserted like so (below.) Thanks for listening and clarifying this!

ngPAWS is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 2 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with this program.  If not, see http://www.gnu.org/licenses/

**Comment by Utodev** [comment]
Hi Scott,

I will take care of this issue, clearly stating that it's GPL v2 or any later.

On the other hand, if you closely  read the text in the readme file, you'll see ngPAWS compiler is licensed using GPL, but ngPAWS libraries are licensed using MIT license, so I'll probably will have to add two different files in the "compiler" folder (GPL) and "jsl" (libraries) folder (MIT). I will add more detail on that on the readme file too.

I cannot do it right now but I will address this issue in the next few days.

Thanks

**Comment by scott-martinez** [comment]
Yes, it's already clear enough, I think, about the two licenses in effect. The ambiguous part, to me, was if the "any later version" thing applied.

**Comment by Utodev** [comment]
Hi Scott,

I've updated the readme file to include the "v2 or later" part. Also, I've added an specific license to the developement IDE, that was added last to the project, and didn't have an specific license.

**Comment by scott-martinez** [comment]
Thank you.
