### ISSUE TITLE
ngPAWS Wiki License

### ISSUE THREAD

**Issue by scott-martinez** [Utodev/ngPAWS#6]
Thanks for placing ngPAWS under the GPL, and letting people modify and change the software.

In reviewing the ngPAWS wiki containing the program's documentation, I found no licensing information there. This means that default copyright would apply: No copying, no modification, etc.

A freely licensed program like ngPAWS should also have freely licensed documentation. See http://www.gnu.org/philosophy/free-doc.en.html for more information.

Can you please add an appropriate free-as-in-freedom license to the wiki allowing for it to be copied/modified/etc. by others? Thanks!

**Comment by Utodev** [comment]
Hi Scott,

I have added license information for the documentation itself in the quick links (sidebar) of the wiki,

License chosen is:

http://creativecommons.org/licenses/by-nc-sa/4.0/

**Comment by scott-martinez** [comment]
Thanks, although I wonder if it can't instead be a free (as-in-freedom) license? If you want to use CC, that would be CC BY or CC BY-SA. The non-commercial part means it remains proprietary.

**Comment by Utodev** [comment]
The license is a free (as in freedom) license, as all CC license are. The non commercial part just means I don't want anyone to make profit of the documentation, though I doubt no one ever does. ngPAWS and it's documentation wants to be both free and free (as in freedom, and as in free beer).

**Comment by scott-martinez** [comment]
"The license is a free (as in freedom) license, as all CC license are."

Actually, not all CC licenses are free-as-freedom. Check out the CC license chooser: http://creativecommons.org/choose/ and you can see.

Notice how, if both adaptations and commercial use are allowed, there is a little blurb that says "This is a free culture license" with a little green badge.

But if either thing of those are changed, noticed how green badge disappears and the message instead changes to it not being a free license.

And so, not all CC licenses are free-as-freedom. Anything containing non-commercial or no-derivatives would be non-free.

Consider that the GPL and MIT licenses allow commercial use (this is covered in the Free Software Definition at http://www.gnu.org/philosophy/free-sw.html where it explains that "Free software" does not mean "noncommercial". A free program must be available for commercial use, commercial development, and commercial distribution. Commercial development of free software is no longer unusual; such free commercial software is very important. You may have paid money to get copies of free software, or you may have obtained copies at no charge. But regardless of how you got your copies, you always have the freedom to copy and change the software, even to sell copies."

But with non-commercial documentation then copies of the docs couldn't be included with the program when it's being distributed commercially, or else violate the license.

This also matches with the article I linked to at the very start: http://www.gnu.org/philosophy/free-doc.en.html which explains that "The criterion for a free manual is pretty much the same as for free software: it is a matter of giving all users certain freedoms. Redistribution (including commercial redistribution) must be permitted, so that the manual can accompany every copy of the program, on line or on paper. Permission for modification is crucial too."

And so, both of these resources (the CC license chooser and gnu.org) both say that commercial use needs to be allowed in order to be free. So, conversely, a license that doesn't would not be.

I realize that this is a lot to cover but you may also found this a good read for arguments against non-commercial licensing: http://freedomdefined.org/Licenses/NC

**Comment by Utodev** [comment]
HI Scott,

Ok, I have read a bit more about licenses, and after checking also with some friends I've reconsidered my position and now I'm using the CC BY-SA  (without the NC part). The documentation has been updated accordingly.

I hope that helps!
