### ISSUE TITLE
Build: Path to ngpc changes in Ubuntu 22.04

### ISSUE THREAD

**Issue by mmartinortiz** [Utodev/ngPAWS#62]
Ubuntu 22.04, Lazarus 2.2.0, during build, `ngpc` is located in a different location.

https://github.com/Utodev/ngPAWS/blob/0a380e282eef6b4ad062868a788887522ef52394/build_linux.sh#L60

Line 60 needs to be replaced with

```bash
mv build/compiler/VisualStudio/.vs/ngpc dist/ngpc
```

After the change, `build_linux.sh` successfully compiles ngPAWS.

**Comment by cibersheep** [comment]
Does this change work for people that doesn't use VisualStudio?
