### ISSUE TITLE
[10 beta][Ubuntu16.04][IDE] Texto cortado en Opciones

### ISSUE THREAD

**Issue by cibersheep** [Utodev/ngPAWS#9]
En español el texto es bastante más largo que en inglés y queda cortado (en inglés un poco justo pero se lee al completo excepto el título Preprocessor [Parameters]).

La ventana no se puede redimensionar (¿cosa de Lazarus?) que podría ser una solución,

![10-beta-opt](https://cloud.githubusercontent.com/assets/6640041/23486063/baa65664-fede-11e6-96ea-80e5305e9c30.png)

**Comment by Utodev** [comment]
Apparently your font size is much larger than the one I use, and I'm afraid that is an effect of your specify "theme". Anyway, I will make the options window bigger in next release so larger fonts can be accomodated within the window. Not a definitive solution as the larger the font, the more difficult will be to fit text inside.

**Comment by cibersheep** [comment]
I see. Then it must be related to Ubuntu Unity and the screen resolution of my laptop. I actually see the general text very small (menu text and txp)... Anyway, now I'm using Geany. If thus is something that only affects me, do not worry :)

**Comment by Utodev** [comment]
It can affect anyone whose font is larger than expected. With linux, having so many desktop engines, themes, etc. is difficult to cover them all. Anyway the next version will have a 800x600 options screen so there will be more room for those texts.
